# Generated by Django 3.2.9 on 2021-12-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waga', models.FloatField()),
                ('wzrost', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='bmi',
        ),
    ]
