# Generated by Django 3.2.9 on 2021-12-17 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0002_auto_20211216_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmimeasurement',
            old_name='waga',
            new_name='height_in_meters',
        ),
        migrations.RenameField(
            model_name='bmimeasurement',
            old_name='wzrost',
            new_name='weight_in_kg',
        ),
    ]
