# Generated by Django 3.2.9 on 2021-12-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0003_auto_20211217_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
