# Generated by Django 3.2.9 on 2021-12-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmi', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='Email',
        ),
    ]
